name: Build & Push AWX EE

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install ansible-builder
        run: pip install ansible-builder

      - name: Get release tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Execution Environment image with release tag
        run: |
          ansible-builder build -v3 --container-runtime podman \
            -t ghcr.io/${{ github.repository_owner }}/awx-ee:${{ steps.get_tag.outputs.tag }}

      - name: Build Execution Environment image with latest tag
        run: |
          ansible-builder build -v3 --container-runtime podman \
            -t ghcr.io/${{ github.repository_owner }}/awx-ee:latest

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push release tag image
        run: podman push ghcr.io/${{ github.repository_owner }}/awx-ee:${{ steps.get_tag.outputs.tag }}

      - name: Push latest image
        run: podman push ghcr.io/${{ github.repository_owner }}/awx-ee:latest
