name: Build & Push AWX EE

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-builder
        run: pip install ansible-builder

      - name: Build Execution Environment image
        run: |
          ansible-builder build -v3 -t ghcr.io/${{ github.repository_owner }}/awx-ee:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io
        run: docker push ghcr.io/${{ github.repository_owner }}/awx-ee:latest
